# Anaconda configuration file for BlazeOS (Fedora Workstation base)

[Profile]
profile_id = fedora-workstation
base_profile = fedora

[Profile Detection]
os_id = fedora
variant_id = workstation

[Payload]
default_environment = workstation-product-environment

[Bootloader]
menu_auto_hide = False

[User Interface]
custom_stylesheet = /usr/share/anaconda/pixmaps/workstation/fedora-workstation.css
hidden_spokes =
    NetworkSpoke
hidden_webui_pages =
    anaconda-screen-network
