#!/usr/bin/sh
set -e

prefix="/usr"
exec_prefix="/usr"
datarootdir="/usr/share"
if [ -f "$pkgdatadir/grub-mkconfig_lib" ]; then
  . "$pkgdatadir/grub-mkconfig_lib"
fi

version_test_gt ()
{
  local a=`echo "$1" | sed -e "s/[^-]*-//"`
  local b=`echo "$2" | sed -e "s/[^-]*-//"`
  [ "$a" = "$b" ] && return 1
  local c=`printf '%s\n' "$a" "$b" | sort -V | head -n 1`
  [ "$c" = "$b" ] && return 0
  return 1
}

latest_version=""
for i in /boot/vmlinuz-* /vmlinuz-* ; do
  [ -f "$i" ] || continue
  version=`echo "$i" | sed -e "s/^.*vmlinuz-//"`
  if [ -z "$latest_version" ] || version_test_gt "$version" "$latest_version"; then
    latest_version="$version"
  fi
done

if [ -n "$latest_version" ]; then
  cat << BERPENTRY
menuentry "Blaze Emergency Recovery Protocol (BERP)" --class recovery --class tool {
	load_video
	set gfxpayload=keep
	insmod gzio
	insmod part_gpt
	insmod btrfs
	search --no-floppy --set=root --file /etc/blazeos-release
	if [ -z "$root" ]; then
		search --no-floppy --set=root -l 'fedora'
	fi
	linux /boot/vmlinuz-${latest_version} ro quiet rhgb console=tty1 systemd.unit=blaze-recovery.target
	initrd /boot/initramfs-${latest_version}.img
}
BERPENTRY
fi
