[Unit]
Description=BlazeOS Emergency Death Screen

[Service]
ExecStartPre=-/usr/bin/plymouth quit
ExecStart=
ExecStart=-/usr/bin/blaze-death-screen
StandardInput=tty-force
StandardOutput=inherit
StandardError=inherit
